package ar.cac.cajero.model;
// Generated 06/07/2018 20:22:37 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuentas generated by hbm2java
 */
public class Cuentas  implements java.io.Serializable {


     private Integer id;
     private Clientes clientes;
     private TiposCuenta tiposCuenta;
     private BigDecimal saldo;
     private boolean habilitado;
     private Set movimientoses = new HashSet(0);

    public Cuentas() {
    }

	
    public Cuentas(Clientes clientes, TiposCuenta tiposCuenta, BigDecimal saldo, boolean habilitado) {
        this.clientes = clientes;
        this.tiposCuenta = tiposCuenta;
        this.saldo = saldo;
        this.habilitado = habilitado;
    }
    public Cuentas(Clientes clientes, TiposCuenta tiposCuenta, BigDecimal saldo, boolean habilitado, Set movimientoses) {
       this.clientes = clientes;
       this.tiposCuenta = tiposCuenta;
       this.saldo = saldo;
       this.habilitado = habilitado;
       this.movimientoses = movimientoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public TiposCuenta getTiposCuenta() {
        return this.tiposCuenta;
    }
    
    public void setTiposCuenta(TiposCuenta tiposCuenta) {
        this.tiposCuenta = tiposCuenta;
    }
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }
    public boolean isHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }
    public Set getMovimientoses() {
        return this.movimientoses;
    }
    
    public void setMovimientoses(Set movimientoses) {
        this.movimientoses = movimientoses;
    }




}


