package ar.cac.cajero.model;
// Generated 06/07/2018 20:22:37 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Movimientos generated by hbm2java
 */
public class Movimientos  implements java.io.Serializable {


     private int id;
     private Cuentas cuentas;
     private TiposMovimiento tiposMovimiento;
     private Date fecha;
     private BigDecimal saldoAnterior;
     private BigDecimal importe;
     private BigDecimal saldoPosterior;

    public Movimientos() {
    }

    public Movimientos(int id, Cuentas cuentas, TiposMovimiento tiposMovimiento, Date fecha, BigDecimal saldoAnterior, BigDecimal importe, BigDecimal saldoPosterior) {
       this.id = id;
       this.cuentas = cuentas;
       this.tiposMovimiento = tiposMovimiento;
       this.fecha = fecha;
       this.saldoAnterior = saldoAnterior;
       this.importe = importe;
       this.saldoPosterior = saldoPosterior;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cuentas getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Cuentas cuentas) {
        this.cuentas = cuentas;
    }
    public TiposMovimiento getTiposMovimiento() {
        return this.tiposMovimiento;
    }
    
    public void setTiposMovimiento(TiposMovimiento tiposMovimiento) {
        this.tiposMovimiento = tiposMovimiento;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getSaldoAnterior() {
        return this.saldoAnterior;
    }
    
    public void setSaldoAnterior(BigDecimal saldoAnterior) {
        this.saldoAnterior = saldoAnterior;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }
    public BigDecimal getSaldoPosterior() {
        return this.saldoPosterior;
    }
    
    public void setSaldoPosterior(BigDecimal saldoPosterior) {
        this.saldoPosterior = saldoPosterior;
    }




}


