package ar.cac.cajero.model;
// Generated 06/07/2018 20:22:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TiposMovimiento generated by hbm2java
 */
public class TiposMovimiento  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private boolean habilitado;
     private Set movimientoses = new HashSet(0);

    public TiposMovimiento() {
    }

	
    public TiposMovimiento(String nombre, boolean habilitado) {
        this.nombre = nombre;
        this.habilitado = habilitado;
    }
    public TiposMovimiento(String nombre, boolean habilitado, Set movimientoses) {
       this.nombre = nombre;
       this.habilitado = habilitado;
       this.movimientoses = movimientoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public boolean isHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }
    public Set getMovimientoses() {
        return this.movimientoses;
    }
    
    public void setMovimientoses(Set movimientoses) {
        this.movimientoses = movimientoses;
    }




}


